### PR TITLE
include typename on templates iterator declaration

### PR DESCRIPTION
**Pull request by diegodgs**

### CODE REVIEW

**Comment by daniel-packard** [comment]
HI @diegodgs --  The changes to CMakeLists.txt have broken a local build of mine because the compiled libraries are no longer installed -- I can fix for my particular situation locally, but I am just curious why the changes were made

Thanks!

**Comment by fabiencastan** [comment]
I have the same problem. Libraries are no more installed.

**Comment by qhull** [comment]
Agreed.  The June, 2016 commit to CMakelists.txt doesn't make sense.

I plan to work on Qhull later this week and will 
try to figure out how it happened.  Others have 
noticed a problem, but I didn't realize it was due to a bad commit.

Many thanks for investigating.

                                 --Brad


At 11:36 AM 3/9/2017, Jamie Snape wrote:

**Comment by pchilds** [comment]
QHull has been broken since this pull request has been accepted due to commit cea6d22011aaa2f5b6341aa966c3db530274f275 sneaking in. Should be a simple matter of cherrypicking it out.

**Pull request merged**
