### PR TITLE
Fix install of executables and libraries

### PR DESCRIPTION
**Pull request by jamiesnape**
PTAL @qhull.

### CODE REVIEW

**Comment by qhull** [comment]
Jamie,

Thanks for your suggestion.   The proposed change would work OK for static users of Qhull, but misses the qhull_SHAREDR target and the deprecated install targets.    

In addition, it overwrites the previous definition of qhull_TARGETS_INSTALL at line 350.   There should only be one definition.    The default should include qhull_SHAREDR.

The default setting should probably exclude the the deprecated install targets.  The deprecated targets for shared libraries should be easily included by setting a user variable or flag.   The previous release included the new api for reentrant Qhull.   TARGETS_INSTALL included the deprecated install targets for backwards  compatibility.

I find it difficult to make the build good for every user (or at least tolerable),   Feel free to try again.

The qhull_TARGETS_INSTALL target will be reviewed for the next release.    Other parts of the build also need rework.    

                              --Brad

**Comment by jamiesnape** [comment]
Brad,

I must be looking at the wrong file. I do not see any other definition of `qhull_TARGETS_INSTALL`:

https://github.com/qhull/qhull/search?utf8=✓&q=qhull_TARGETS_INSTALL

especially not on line 350:

https://github.com/qhull/qhull/blob/master/CMakeLists.txt#L350

Also, nothing actually installs other than headers if you run the build

Can you re-open this so we can iterate on this to add `qhull_SHAREDR` to the list (an oversight) and continue the conversation? Seems unusual to have to create a new PR instead of fixing an existing one.

Jamie

**Comment by jamiesnape** [comment]
Actually, you are missing an `add_library` call and not even building `qhull_SHAREDR`, which would be why I did not install it.

**Comment by qhull** [comment]
Hi Jamie,

Maybe there is a mistake in what I pushed as 
'master'.  I'll need to investigate.  My copy 
includes an add_library call on line 364.

                                 --Brad

At 04:13 PM 3/5/2017, Jamie Snape wrote:

**Comment by jamiesnape** [comment]
This commit seems to be the issue:

https://github.com/qhull/qhull/commit/cea6d22011aaa2f5b6341aa966c3db530274f275

Not sure the purpose, but it removed the build of many targets and the install. Hence, the CMake build is not really usable now.

**Comment by daizr** [comment]
@qhull would you be willing to reconsider this pr? im using @jamiesnape fork to `.deb` package qhull since it builds/installs everything properly for me (confirmed to work w/ ubuntu 14 and 16).

**Pull request closed without merging**
