### PR TITLE
Include new symbols from accessors_r.h in qhull_r-exports.def

### PR DESCRIPTION
**Pull request by JuhaHeiskala**
Windows version of the library is missing the symbols added in [libqhull_r.h](https://github.com/qhull/qhull/blob/master/src/libqhull_r/libqhull_r.h) by @stevengj.
This PR adds the new symbols in [qhull_r-exports.def](https://github.com/qhull/qhull/blob/master/src/libqhull_r/qhull_r-exports.def)

### CODE REVIEW

**Comment by stevengj** [comment]
Bump.

**Comment by stevengj** [comment]
bump

**Comment by thchr** [comment]
Bump: would be great to have this merged.

**Comment by cbbarber** [comment]
Sorry for the delay.  Thanks for the prompting.   Feel free to post additional pull requests as needed.

**Comment by JuhaHeiskala** [comment]
Thanks for the merge.

**Pull request merged**
