### PR TITLE
Add pkg-config support

### PR DESCRIPTION
**Pull request by roehling**
This PR implements the wishlist bug from #22. The pkg-config file format
is pretty simple, it basically provides a bunch of compiler flags to
compile and link against a library.

I changed the default INSTALL_DIR locations to relative paths, because
CMake expands relative paths to the CMAKE_INSTALL_PREFIX by default
anyway, and it makes it possible to have both the CMake config and the
pkg-config in a relocateable style.

Most of the magic happens in the foreach() loop, which is a semicolon
separated list of config values for the qhull.pc.in template in the form
NAME;DESCRIPTION

### CODE REVIEW

**Comment by cbbarber** [comment]
Hi Timo,

Do you know if pkg-config is available in the Windows MSYS2 or, equivalently Git for Windows environment?   I also have access to a Debian GNU/Linux environment with dpkg.   Is pkg-config available?

In any case, please supply the instructions from building Qhull using pkg-config.  I preparing the Qhull-2020.1 release.

            --Brad

**Comment by roehling** [comment]
Hi Brad,

pkg-config is not meant for building Qhull, it's a way to supply compiler flags, so users can link against Qhull libraries. The pkg-config executable queries the .pc config files and outputs those flags (merging flags from multiple query options), e.g.,

    $ pkg-config --cflags --libs qhull_r
    -I/usr/local/include -lqhull_r

With the backtick operator that replaces parts of a command line with the output of a program, you can even compile and link a single-source application against (say) libqhull_r with a one-liner:

    gcc `pkg-config --cflags --libs qhull_r` -o my_app my_app.c

This is mostly a convenience for people who can't use CMake (which provides a superior method via exported targets). If you mention something like "added pkg-config support to link against Qhull libraries" in your release notes, it will most likely be enough for anyone who wants to use this.

Cheers
Timo

**Comment by cbbarber** [comment]
Thanks Timo.   

What is the relationship between qhull.pc.in and CMakeLists.txt?   Does pkg-config read CMakeLists.txt, or does CMake need to run to initialize qhull.pc.in?

Does pkg-config also help with Qhull's C++ interface?  If so, please provide an example command line (like your gcc one-liner above).

                                        --Brad

At 05:36 AM 05/24/2020, you wrote:

**Comment by roehling** [comment]
CMake creates one .pc file per library from the qhull.pc.in template and installs them to the well-known location `$PREFIX/lib/pkgconfig` ([here](https://github.com/qhull/qhull/blob/master/CMakeLists.txt#L664-L677) are the relevant `CMakeLists.txt` lines).

For the C++ interface, you'd use

    g++ `pkg-config --cflags --libs qhullcpp qhullstatic_r` -o my_app my_app.cpp

or

    g++ `pkg-config --cflags --libs qhullcpp qhull_r` -o my_app my_app.cpp

**Comment by cbbarber** [comment]
Timo,

Would it be easy to .pc file generation to the install target for the top-level Makefile?  It would need to be conditional on pkg-config, or else a separate target.   If so, is this something you could do?  The various build options should produce the same results.

                                --Brad

At 05:21 PM 05/24/2020, you wrote:

**Comment by roehling** [comment]
Sure, I think that can be done with a little bit of sed magic. I'll have a look at the Makefile and create a PR for that.

**Pull request merged**
