### PR TITLE
Install html documentation in the right places.

### PR DESCRIPTION
**Pull request by niclasr**
The html documentation is currently installed in the include directories?
The links in the html files also dpn't work (../../html...). 
With this patch the links work as expected.

### CODE REVIEW

**Comment by niclasr** [comment]
Hi again my pull request is still wrong. Sorry for the noise.

**Comment by qhull** [comment]
There are two sets of documents --  1) documentation in qhull/html/*.htm with the Manual at qhull/html/index.htm  2) Code documentation in qhull/src/libqhull/*.htm and qhull/src/libqhull_r/*.htm.

I use the .htm as is, so there may be a problem when they are installed.   Let me know if you figure out the best plan.

**Comment by qhull** [comment]
There are two sets of documents --  1) documentation in qhull/html/*.htm with the Manual at qhull/html/index.htm  2) Code documentation in qhull/src/libqhull/*.htm and qhull/src/libqhull_r/*.htm.

I use the .htm as is, so there may be a problem when they are installed.   Let me know if you figure out the best plan.

**Comment by qhull** [comment]
No worry.

There are two sets of documents --  1) 
documentation in qhull/html/*.htm with the Manual 
at qhull/html/index.htm  2) Code documentation in 
qhull/src/libqhull/*.htm and qhull/src/libqhull_r/*.htm.

I use the .htm as is, so there may be a problem 
when they are installed.   Let me know if you figure out the best plan.

                                 --Brad


At 11:47 AM 1/19/2016, Niclas Rosenvik wrote:

**Pull request closed without merging**
